services:
  - type: web
    name: regularise-riderid
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: node server/server.js
    domains:
      - myvault.com.ng
    disk:
      name: rider-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONNIFY_API_KEY
        sync: false
      - key: MONNIFY_SECRET_KEY
        sync: false
      - key: MONNIFY_CONTRACT_CODE
        sync: false
      - key: GOOGLE_SCRIPT_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: BASE_URL
        value: https://myvault.com.ng
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ENCRYPTION_KEY
        value: 815125701ab168789636b04b231f30dc6af0c5e72e17d4fbb57f1ce2dcde4d6a
